#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'java'
cookbook 'ruby_build'
cookbook 'rbenv',             :git => 'https://github.com/fnichol/chef-rbenv',
                              :ref => 'v0.6.6'
