---
aws_access_key_id: my_access_key_id
aws_secret_access_key: my_secret_access_key
s3_bucket: /my/bucket
vagrant_boxes:
  - precise32
  - precise64
  - lucid32
  - lucid64
  - oneiric32
  - oneiric64
  - natty32
  - natty64
  - maverick32
  - maverick64
rbenv_rubies:
  - 1.8.7-p375
  - 1.9.3-p545
  - 2.0.0-p451
  - 2.1.1
  - jruby-1.7.11
  - ree-1.8.7-2012.02
